version: '3'
services:
  api:
    image: node:16.15.1
    command: sh -c 'npm install && npm run server:dev'     
    container_name: api
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - sqs
  db:
    container_name: db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pg-dataset:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  sqs:
    image: s12v/elasticmq
    container_name: sqs
    volumes:
      - ./elasticmq/custom.conf:/etc/elasticmq/elasticmq.conf
    ports:
      - "9324:9324"

volumes:
  pg-dataset: