image: node:16.15.1
pipelines:
    default:
      - step:
          name: test
          caches:
            - node
          script:
            - apt-get update
            - apt-get install postgresql-client -y
            - cd functions
            - npm install
            - sh create-db.sh test
            - sh run_migration.sh test
            - echo "Completed"
          services:
            - postgres
definitions:
  services:
    postgres:
      image: postgres:latest
      variables:
        POSTGRES_USER: 'root'
        POSTGRES_PASSWORD: 'root'