version: '3'
services:
  api:
    image: node:16.16.0
    command: sh -c 'npm install && npm run server --env=dev'
    container_name: api
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      # - sqs
  db:
    container_name: db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pg-dataset:/var/lib/postgresql/data
  # sqs:
  #   image: s12v/eulasticmq
  #   container_name: sqs
  #   volumes:
  #     - ./elasticmq/custom.conf:/etc/elasticmq/elasticmq.conf
  #   ports:
  #     - "9324:9324"
  # cron:
  #   image: node:16.16.0
  #   command: sh -c 'npm install && npm run cron --env=dev'
  #   container_name: cron
  #   working_dir: /cron
  #   volumes:
  #     - .:/cron
volumes:
  pg-dataset:
